GET http://localhost:4000/posts
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZmVyaWFuIiwiaWF0IjoxNjcwOTQyODI2fQ.X2lX3e15qXAXCyzKkoQpAYYrmUi-I-s7F4SJITuJQgM


###
POST http://localhost:4000/login 
Content-Type: application/json

{
    "username": "ferian"
}