GET http://localhost:4000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZmVyaWFuIiwiaWF0IjoxNjcxMDA3MDM1LCJleHAiOjE2NzEwMDcwNjV9.H3bxC3_B9PRC7Bx3cE71xDznVKTprr3Cye0Gvys8LBs
###

POST http://localhost:5000/login
Content-Type: application/json

{
    "username":"ferian"
}
####
POST http://localhost:5000/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZmVyaWFuIiwiaWF0IjoxNjcxMDA3MDUyfQ.Br5NZ0C4Nl1qjK9ePL9ZbZlsSiYIf8UKzbldCGVeVw8"

}

###
DELETE  http://localhost:5000/logout
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZmVyaWFuIiwiaWF0IjoxNjcxMDA3MDUyfQ.Br5NZ0C4Nl1qjK9ePL9ZbZlsSiYIf8UKzbldCGVeVw8"
}